version: '2.1'

services:
  # 后端
  pricehub.server:
    # 需要自行编译（进入 server 执行 ./build.sh ）并使用本地镜像：fabric-genshin.server:latest
    image: pricehub.server:latest
    container_name: pricehub.server
    ports:
      - "8888:8888"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai
  # 前端
  pricehub.web:
    # 需要自行编译（进入 web 执行 ./build.sh ）并使用本地镜像：fabric-genshin.web:latest
    image: pricehub.web:latest
    container_name: pricehub.web
    ports:
      - "8000:80"