version: '2.1'

services:
  pricehub.server:
    image: pricehub.server:latest
    container_name: pricehub.server
    # build:
    #   context: server
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pricehub
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - TZ=Asia/Shanghai
    depends_on:
      - mysql
      - selenium-chrome
    networks:
      - pricehub-network

  pricehub.web:
    image: pricehub.web:latest
    container_name: pricehub.web
    # build:
    #   context: web
    #   dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - pricehub.server
    networks:
      - pricehub-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # 允许空密码
      - MYSQL_DATABASE=pricehub         # 创建 pricehub 数据库
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pricehub-network

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"  # Selenium Server 的默认端口
    networks:
      - pricehub-network

networks:
  pricehub-network:
    driver: bridge

volumes:
  mysql_data: