version: '2.1'

networks:
  fabric_network:
    external:
      name: fabric_network

services:
  # 后端
  fabric-genshin.server:
    # 需要自行编译（进入 server 执行 ./build.sh ）并使用本地镜像：fabric-genshin.server:latest
    image: fabric-genshin.server:latest
    container_name: fabric-genshin.server
    ports:
      - "8888:8888"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai
      - ./../network/crypto-config:/network/crypto-config
    networks:
      - fabric_network
  # 前端
  fabric-genshin.web:
    # 需要自行编译（进入 web 执行 ./build.sh ）并使用本地镜像：fabric-genshin.web:latest
    image: fabric-genshin.web:latest
    container_name: fabric-genshin.web
    ports:
      - "8000:80"
    networks:
      - fabric_network