name: Build Docker Image

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ] # 当推送到 main 分支时触发
  pull_request:
    branches: [ main ] # 当 Pull Request 到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境中运行

    steps:
      # 1. 检出代码
      - name: Check out code
        uses: actions/checkout@v2

      # 2. 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # 使用 GitHub Secrets 中的 Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 使用 GitHub Secrets 中的 Docker Hub 密码
      
      # # 检查构建上下文
      # - name: Check build context
      #   run: |
      #     ls -l
        # ls -l ./server

      # 4. 构建并推送 application.web 镜像
      - name: Build and push pricehub.web
        uses: docker/build-push-action@v2
        with:
          context: web # 构建上下文为 web 目录
          push: true # 推送镜像到 Docker Hub
          tags: thorin215/pricehub.web:latest # 镜像标签

      # 3. 构建并推送 pri.server 镜像
      - name: Build and push pricehub.server
        uses: docker/build-push-action@v2
        with:
          context: server # 构建上下文为 server 目录
          push: true # 推送镜像到 Docker Hub
          tags: thorin215/pricehub.server:latest # 镜像标签


